const fetch = require("node-fetch");

module.exports = async (context) => {
    const { client, m, text, botname } = context;

    if (!text) {
        await client.sendMessage(m.chat, { text: '✳️ *Please provide a prompt to generate an AI image!*\n\n📌 *Example:* `.text2img anime girl with white hair, fantasy theme, high quality`' }, { quoted: m });
        return;
    }

    const apiUrl = `https://api.ryzendesu.vip/api/ai/v2/text2img?prompt=${encodeURIComponent(text)}&model=flux_dev`;

    try {
        await client.sendMessage(m.chat, { react: { text: '⏳', key: m.key } });

        let response = await fetch(apiUrl, {
            headers: { "accept": "image/png" }
        });

        if (!response.ok) throw new Error('⚠️ *Failed to fetch AI image.*');

        let imageBuffer = await response.buffer();

        let caption = `✨ *AI Image Generated!*\n\n🎨 *Prompt:* ${text}\n🤖 *Generated by:* ${botname}\n\n⚡ *Powered by VOXNET.INC*`;

        await client.sendMessage(m.chat, {
            image: imageBuffer,
            caption,
            contextInfo: {
                externalAdReply: {
                    title: "VOX-MD AI Image Generator",
                    body: "Click to explore more AI features!",
                    mediaType: 1,
                    thumbnail: imageBuffer,
                    sourceUrl: "https://voxnet.inc"
                }
            }
        }, { quoted: m });

        await client.sendMessage(m.chat, { react: { text: '✅', key: m.key } });

    } catch (error) {
        console.error('AI Image Generation Error:', error);
        await client.sendMessage(m.chat, { text: '⚠️ *Sorry, failed to generate an image. Please try again later.*' }, { quoted: m });
        await client.sendMessage(m.chat, { react: { text: '❌', key: m.key } });
    }
};
